### ISSUE TITLE
Infinite recurions

### ISSUE THREAD

**Issue by zlatozar** [inaimathi/cl-kanren-trs#2]
This query cause infinite recursion:

``` cl
(run nil (q)
   (== q `(,q))))
```

but should return '()

**Comment by cage2** [comment]
On Fri, Oct 30, 2015 at 10:05:08AM -0700, Zlatozar Zhelyazkov wrote:

Hello!

> This query cause infinite recursion:
> 
> ``` cl
> (run nil (q)
>    (== q `(,q))))
> ```
> 
> but should return '()

I am not so sure, "The  Reasoned Schemer" at page 141 explicitly state
that this expression has no value (9.61).

Later in the  same page you can  find that you should  use ==-check to
get a results:

(run nil (q)
  (==-check q `(,q)))

Unfortunately   this  version   of   minikanren   lacks  a   functions
"occurs-check" and  the expression below  will not works, but  you can
find  a working  version in  this forks  (I will  make a  pull request
ASAP):

https://github.com/cage2/cl-kanren-trs/

here's the expression in the test suite:

https://github.com/cage2/cl-kanren-trs/blob/master/tests/kanren-tests.lisp#L752

Hope this helps!
Bye!
C.

**Comment by zlatozar** [comment]
Very helpful!

Thank you,
Zlatozar
